name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run eunit
      run: rebar3 eunit
    - name: Run ct
      run: rebar3 ct
    - name: Trigger AWS Docker Deploy
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_GHA_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-aws-docker-deploy
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
